import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Header from "./components/Header/header";
import { getUserSession } from "@/lib/session";
import OverLay from "./components/overlay";
import { components } from "@/utils/overlayComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUserSession();
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <AntdRegistry>
            <OverLay Component={components} />
            <Header user={user} />
            <div className="flex justify-center">
              <div className="w-[80%] mt-5">{children}</div>
            </div>
          </AntdRegistry>
        </body>
      </html>
    </StoreProvider>
  );
}
