import { Tag } from "@/app/types/tag/tag";
import { CreatePlanEntity } from "./entities/plan";
import { responseAPI } from "./entities/response";

export const googleLogo = "/thirdPartyLogo/Google.png";
export const facebookLogo = "/thirdPartyLogo/Facebook.png";
export const avatar = "/avatar/avatar.jpg";
export const wallpaper = "/wallpaper/wallpaper.webp";
export const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID!;
export const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET!;
export const FACEBOOK_CLIENT_ID = process.env.FACEBOOK_CLIENT_ID!;
export const FACEBOOK_CLIENT_SECRET = process.env.FACEBOOK_CLIENT_SECRET!;
// export const SERVER_BASE_URL = "https://bootcamp-3.onrender.com/v1/api";
export const SERVER_BASE_URL =
  "https://2f81-2001-ee0-4f93-8f20-5015-fb89-e953-e57b.ngrok-free.app/v1/api";
export const BASE_URL = "localhost:3000";
export const NEXTAUTH_SECRET = process.env.NEXTAUTH_SECRET!;

export const activitiesTags: Tag[] = [
  {
    id: 1,
    name: "Du lịch biển đảo",
  },
  {
    id: 2,
    name: "Du lịch sinh thái",
  },
  {
    id: 3,
    name: "Du lịch tâm linh",
  },
  {
    id: 4,
    name: "Du lịch giải trí",
  },
  {
    id: 5,
    name: "Địa danh lịch sử",
  },
  {
    id: 6,
    name: "Vãn cảnh & Check-in",
  },
  {
    id: 7,
    name: "Du lịch văn hóa & nghệ thuật",
  },
];

export const amentitiesTags: Tag[] = [
  {
    id: 0,
    name: "Bữa sáng",
  },
  {
    id: 1,
    name: "Wifi miễn phí",
  },
  {
    id: 2,
    name: "Bãi đậu xe",
  },
  {
    id: 3,
    name: "Nước uống chào đón",
  },
  {
    id: 4,
    name: "Nhận phòng nhanh",
  },
  {
    id: 5,
    name: "Phòng tập miễn phí",
  },
  {
    id: 6,
    name: "Phòng tập",
  },
  {
    id: 7,
    name: "Vào hồ bơi miễn phí",
  },
  {
    id: 8,
    name: "Wifi cao cấp miễn phí",
  },
  {
    id: 9,
    name: "Nhận phòng trễ",
  },
  {
    id: 10,
    name: "Thuê xe máy",
  },
  {
    id: 11,
    name: "Giảm giá spa",
  },
  {
    id: 12,
    name: "Bao gồm bữa tối",
  },
  {
    id: 13,
    name: "Free mini bar",
  },
  {
    id: 14,
    name: "Trả phòng muộn",
  },
  {
    id: 15,
    name: "Thuê xe đạp",
  },
  {
    id: 16,
    name: "Bữa sáng món chay",
  },
  {
    id: 17,
    name: "Nhận phòng sớm",
  },
  {
    id: 18,
    name: "Khử trùng phòng",
  },
  {
    id: 19,
    name: "Đưa ra sân bay",
  },
  {
    id: 20,
    name: "Car rental",
  },
  {
    id: 21,
    name: "Pool",
  },
  {
    id: 22,
    name: "Free sauna access",
  },
  {
    id: 23,
    name: "Giảm giá đồ ăn uống",
  },
  {
    id: 24,
    name: "Limited housekeeping",
  },
  {
    id: 25,
    name: "Local Bữa sáng",
  },
  {
    id: 26,
    name: "Quà miễn phí",
  },
  {
    id: 27,
    name: "Meeting Room",
  },
  {
    id: 28,
    name: "Bike rental",
  },
  {
    id: 29,
    name: "Afternoon tea",
  },
  {
    id: 30,
    name: "Vegetarian Bữa sáng",
  },
  {
    id: 31,
    name: "All Inclusive",
  },
];

export const testData: responseAPI<CreatePlanEntity> = {
  message: "create plan success",
  status: "200",
  messageData: {
    start_day: "2024-05-24",
    end_day: "2024-05-30",
    start_point: "Hồ Chí Minh",
    end_point: "Đà Nẵng",
    detailPlans: [
      {
        activities: [
          {
            id: 591,
            name: "Bảo tàng Điêu khắc Chăm Đà Nẵng",
            rating: 4.1,
            num_comment: 6200,
            price: 60000,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipPyojT2sFFO6SAH1vbv-KyDi6_JmlLLipT-bxBh=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0602849', '108.1408659')",
            type_activity: "Du lịch văn hóa & nghệ thuật",
            openTime: "07:00",
            closeTime: "17:00",
          },
          {
            id: 605,
            name: "Cầu Tình Yêu Đà Nẵng",
            rating: 4.4,
            num_comment: 2900,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipPnbHQwz-1XWuv7ys_pGrD9ZcvrqueahyBDxZ-X=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0631961', '108.1471896')",
            type_activity: "Vãn cảnh & Check-in",
            openTime: "07:00",
            closeTime: "12:00",
          },
          {
            id: 623,
            name: "Chợ Đêm Sơn Trà",
            rating: 4,
            num_comment: 8400,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipPszW-wO0KJr897Iq0q8ksQF3bun4idkiYGUC1H=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.061582', '108.1495837')",
            type_activity: "Du lịch văn hóa & nghệ thuật",
            openTime: "18:00",
            closeTime: "00:00",
          },
          {
            id: 634,
            name: "Bảo tàng Đà Nẵng",
            rating: 4,
            num_comment: 1800,
            price: 20000,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipOYN3XIgJ6KheNrpDdnK0ffkoZZ9fkWG2wCzkE6=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0764304', '108.1390849')",
            type_activity: "Du lịch văn hóa & nghệ thuật",
            openTime: "08:00",
            closeTime: "17:00",
          },
          {
            id: 620,
            name: "Bảo tàng Mỹ thuật Đà Nẵng",
            rating: 4.4,
            num_comment: 867,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipMhHD8Vd_sobSHFfzymhzdVFScwDroyjVKHO4_r=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0711719', '108.1355393')",
            type_activity: "Du lịch văn hóa & nghệ thuật",
            openTime: "08:00",
            closeTime: "17:00",
          },
          {
            id: 604,
            name: "Chợ Cồn",
            rating: 4.2,
            num_comment: 16000,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipPQil9Tr-ZhS6ZyeB_JssO0_ckiL9mepbinePin=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0677202', '108.1320649')",
            type_activity: "Du lịch văn hóa & nghệ thuật",
            openTime: "07:00",
            closeTime: "19:00",
          },
          {
            id: 634,
            name: "Bảo tàng Đà Nẵng",
            rating: 4,
            num_comment: 1800,
            price: 20000,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipOYN3XIgJ6KheNrpDdnK0ffkoZZ9fkWG2wCzkE6=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0764304', '108.1390849')",
            type_activity: "Du lịch văn hóa & nghệ thuật",
            openTime: "08:00",
            closeTime: "17:00",
          },
          {
            id: 590,
            name: "Cầu Sông Hàn",
            rating: 4.6,
            num_comment: 4300,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipPR0yFg71ydHaR3xXbbMApGnySOSmF5IBCXeWmc=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.072102', '108.1444452')",
            type_activity: "Vãn cảnh & Check-in",
            openTime: "07:00",
            closeTime: "17:00",
          },
          {
            id: 611,
            name: "Chợ Hàn",
            rating: 3.9,
            num_comment: 28000,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipPbZzr5tU8JU-e3aCbjfRFK_a4TxXxsMqFbnDLY=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0681801', '108.1418199')",
            type_activity: "Du lịch văn hóa & nghệ thuật",
            openTime: "06:00",
            closeTime: "19:00",
          },
          {
            id: 634,
            name: "Bảo tàng Đà Nẵng",
            rating: 4,
            num_comment: 1800,
            price: 20000,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipOYN3XIgJ6KheNrpDdnK0ffkoZZ9fkWG2wCzkE6=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0764304', '108.1390849')",
            type_activity: "Du lịch văn hóa & nghệ thuật",
            openTime: "08:00",
            closeTime: "17:00",
          },
          {
            id: 620,
            name: "Bảo tàng Mỹ thuật Đà Nẵng",
            rating: 4.4,
            num_comment: 867,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipMhHD8Vd_sobSHFfzymhzdVFScwDroyjVKHO4_r=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0711719', '108.1355393')",
            type_activity: "Du lịch văn hóa & nghệ thuật",
            openTime: "08:00",
            closeTime: "17:00",
          },
          {
            id: 608,
            name: "Giáo Xứ Chính Toà Đà Nẵng",
            rating: 4.4,
            num_comment: 1000,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipMOFpSG2yBE4HmugzkjGFaNJvouLAgn1Y6lc7po=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0666664', '108.1408159')",
            type_activity: "Du lịch tâm linh",
            openTime: "07:00",
            closeTime: "18:00",
          },
          {
            id: 622,
            name: "Charming Danang Show",
            rating: 3.9,
            num_comment: 745,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipOu-k4P_bA4hiJWHrtSup_9-CLCVjYDnj5rFAzq=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0267031', '108.1385502')",
            type_activity: "Du lịch văn hóa & nghệ thuật",
            openTime: "07:00",
            closeTime: "17:00",
          },
          {
            id: 588,
            name: "Asia Park - Công viên Châu Á",
            rating: 4.4,
            num_comment: 9700,
            price: 150000,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipNY92dZpYZyZf8Qc8iGcO5FhWf-BBSV5bOPUkSl=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0382391', '108.1458155')",
            type_activity: "Du lịch giải trí",
            openTime: "15:00",
            closeTime: "22:00",
          },
          {
            id: 621,
            name: "Chợ đêm Helio (Khu Ẩm thực đêm Helio）",
            rating: 4.1,
            num_comment: 5000,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipOYdBvPT7Eg6HumRdGpZy1aaN3AMKgzz_yxWp5G=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.037228', '108.1420796')",
            type_activity: "Du lịch văn hóa & nghệ thuật",
            openTime: "17:30",
            closeTime: "22:30",
          },
          {
            id: 622,
            name: "Charming Danang Show",
            rating: 3.9,
            num_comment: 745,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipOu-k4P_bA4hiJWHrtSup_9-CLCVjYDnj5rFAzq=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0267031', '108.1385502')",
            type_activity: "Du lịch văn hóa & nghệ thuật",
            openTime: "07:00",
            closeTime: "17:00",
          },
          {
            id: 588,
            name: "Asia Park - Công viên Châu Á",
            rating: 4.4,
            num_comment: 9700,
            price: 150000,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipNY92dZpYZyZf8Qc8iGcO5FhWf-BBSV5bOPUkSl=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0382391', '108.1458155')",
            type_activity: "Du lịch giải trí",
            openTime: "15:00",
            closeTime: "22:00",
          },
          {
            id: 614,
            name: "Chợ Bắc Mỹ An",
            rating: 4.3,
            num_comment: 3800,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipN4erhNPoFU26rHO2ocWr-wSXyChTqGPSfhlDLw=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0415616', '108.1598646')",
            type_activity: "Du lịch văn hóa & nghệ thuật",
            openTime: "06:00",
            closeTime: "19:00",
          },
        ],
        hotel: {
          id: 77,
          name: "M Village Đinh Công Tráng",
          price: 6480,
          rating: 9.3,
          address: "Đà Nẵng",
        },
        transport: {
          flights: [
            {
              departure_airport: {
                name: "Tan Son Nhat International Airport",
                id: "SGN",
                time: "2024-05-24 08:05",
              },
              arrival_airport: {
                name: "Da Nang International Airport",
                id: "DAD",
                time: "2024-05-24 09:30",
              },
              duration: 85,
              airplane: "Airbus A321",
              airline: "Vietravel Airlines",
              airline_logo:
                "https://www.gstatic.com/flights/airline_logos/70px/VU.png",
              travel_class: "Economy",
              flight_number: "VU 672",
              extensions: ["Carbon emissions estimate: 76 kg"],
            },
          ],
          total_duration: 85,
          carbon_emissions: {
            this_flight: 76000,
            typical_for_this_route: 78000,
            difference_percent: -3,
          },
          price: 2156080,
          type: "Round trip",
          airline_logo:
            "https://www.gstatic.com/flights/airline_logos/70px/VU.png",
          departure_token:
            "WyJDalJJYldScmFqWlVMVWd4UXpoQlEwbDRaRkZDUnkwdExTMHRMUzB0TFc5NWRtWXlNVUZCUVVGQlIxcE5XR05KUjIxc2VITkJFZ1ZXVlRZM01ob01DTERNZ3dFUUFCb0RWazVFT0J4d2xFST0iLFtbIlNHTiIsIjIwMjQtMDUtMjQiLCJEQUQiLG51bGwsIlZVIiwiNjcyIl1dXQ==",
        },
        total: 230000,
      },
      {
        activities: [
          {
            id: 634,
            name: "Bảo tàng Đà Nẵng",
            rating: 4,
            num_comment: 1800,
            price: 20000,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipOYN3XIgJ6KheNrpDdnK0ffkoZZ9fkWG2wCzkE6=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0764304', '108.1390849')",
            type_activity: "Du lịch văn hóa & nghệ thuật",
            openTime: "08:00",
            closeTime: "17:00",
          },
          {
            id: 590,
            name: "Cầu Sông Hàn",
            rating: 4.6,
            num_comment: 4300,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipPR0yFg71ydHaR3xXbbMApGnySOSmF5IBCXeWmc=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.072102', '108.1444452')",
            type_activity: "Vãn cảnh & Check-in",
            openTime: "07:00",
            closeTime: "17:00",
          },
          {
            id: 611,
            name: "Chợ Hàn",
            rating: 3.9,
            num_comment: 28000,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipPbZzr5tU8JU-e3aCbjfRFK_a4TxXxsMqFbnDLY=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0681801', '108.1418199')",
            type_activity: "Du lịch văn hóa & nghệ thuật",
            openTime: "06:00",
            closeTime: "19:00",
          },
          {
            id: 590,
            name: "Cầu Sông Hàn",
            rating: 4.6,
            num_comment: 4300,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipPR0yFg71ydHaR3xXbbMApGnySOSmF5IBCXeWmc=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.072102', '108.1444452')",
            type_activity: "Vãn cảnh & Check-in",
            openTime: "07:00",
            closeTime: "17:00",
          },
          {
            id: 605,
            name: "Cầu Tình Yêu Đà Nẵng",
            rating: 4.4,
            num_comment: 2900,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipPnbHQwz-1XWuv7ys_pGrD9ZcvrqueahyBDxZ-X=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0631961', '108.1471896')",
            type_activity: "Vãn cảnh & Check-in",
            openTime: "07:00",
            closeTime: "12:00",
          },
          {
            id: 623,
            name: "Chợ Đêm Sơn Trà",
            rating: 4,
            num_comment: 8400,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipPszW-wO0KJr897Iq0q8ksQF3bun4idkiYGUC1H=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.061582', '108.1495837')",
            type_activity: "Du lịch văn hóa & nghệ thuật",
            openTime: "18:00",
            closeTime: "00:00",
          },
          {
            id: 634,
            name: "Bảo tàng Đà Nẵng",
            rating: 4,
            num_comment: 1800,
            price: 20000,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipOYN3XIgJ6KheNrpDdnK0ffkoZZ9fkWG2wCzkE6=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0764304', '108.1390849')",
            type_activity: "Du lịch văn hóa & nghệ thuật",
            openTime: "08:00",
            closeTime: "17:00",
          },
          {
            id: 620,
            name: "Bảo tàng Mỹ thuật Đà Nẵng",
            rating: 4.4,
            num_comment: 867,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipMhHD8Vd_sobSHFfzymhzdVFScwDroyjVKHO4_r=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0711719', '108.1355393')",
            type_activity: "Du lịch văn hóa & nghệ thuật",
            openTime: "08:00",
            closeTime: "17:00",
          },
          {
            id: 608,
            name: "Giáo Xứ Chính Toà Đà Nẵng",
            rating: 4.4,
            num_comment: 1000,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipMOFpSG2yBE4HmugzkjGFaNJvouLAgn1Y6lc7po=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0666664', '108.1408159')",
            type_activity: "Du lịch tâm linh",
            openTime: "07:00",
            closeTime: "18:00",
          },
          {
            id: 590,
            name: "Cầu Sông Hàn",
            rating: 4.6,
            num_comment: 4300,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipPR0yFg71ydHaR3xXbbMApGnySOSmF5IBCXeWmc=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.072102', '108.1444452')",
            type_activity: "Vãn cảnh & Check-in",
            openTime: "07:00",
            closeTime: "17:00",
          },
          {
            id: 620,
            name: "Bảo tàng Mỹ thuật Đà Nẵng",
            rating: 4.4,
            num_comment: 867,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipMhHD8Vd_sobSHFfzymhzdVFScwDroyjVKHO4_r=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0711719', '108.1355393')",
            type_activity: "Du lịch văn hóa & nghệ thuật",
            openTime: "08:00",
            closeTime: "17:00",
          },
          {
            id: 604,
            name: "Chợ Cồn",
            rating: 4.2,
            num_comment: 16000,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipPQil9Tr-ZhS6ZyeB_JssO0_ckiL9mepbinePin=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0677202', '108.1320649')",
            type_activity: "Du lịch văn hóa & nghệ thuật",
            openTime: "07:00",
            closeTime: "19:00",
          },
          {
            id: 622,
            name: "Charming Danang Show",
            rating: 3.9,
            num_comment: 745,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipOu-k4P_bA4hiJWHrtSup_9-CLCVjYDnj5rFAzq=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0267031', '108.1385502')",
            type_activity: "Du lịch văn hóa & nghệ thuật",
            openTime: "07:00",
            closeTime: "17:00",
          },
          {
            id: 588,
            name: "Asia Park - Công viên Châu Á",
            rating: 4.4,
            num_comment: 9700,
            price: 150000,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipNY92dZpYZyZf8Qc8iGcO5FhWf-BBSV5bOPUkSl=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0382391', '108.1458155')",
            type_activity: "Du lịch giải trí",
            openTime: "15:00",
            closeTime: "22:00",
          },
          {
            id: 621,
            name: "Chợ đêm Helio (Khu Ẩm thực đêm Helio）",
            rating: 4.1,
            num_comment: 5000,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipOYdBvPT7Eg6HumRdGpZy1aaN3AMKgzz_yxWp5G=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.037228', '108.1420796')",
            type_activity: "Du lịch văn hóa & nghệ thuật",
            openTime: "17:30",
            closeTime: "22:30",
          },
          {
            id: 622,
            name: "Charming Danang Show",
            rating: 3.9,
            num_comment: 745,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipOu-k4P_bA4hiJWHrtSup_9-CLCVjYDnj5rFAzq=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0267031', '108.1385502')",
            type_activity: "Du lịch văn hóa & nghệ thuật",
            openTime: "07:00",
            closeTime: "17:00",
          },
          {
            id: 588,
            name: "Asia Park - Công viên Châu Á",
            rating: 4.4,
            num_comment: 9700,
            price: 150000,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipNY92dZpYZyZf8Qc8iGcO5FhWf-BBSV5bOPUkSl=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0382391', '108.1458155')",
            type_activity: "Du lịch giải trí",
            openTime: "15:00",
            closeTime: "22:00",
          },
          {
            id: 614,
            name: "Chợ Bắc Mỹ An",
            rating: 4.3,
            num_comment: 3800,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipN4erhNPoFU26rHO2ocWr-wSXyChTqGPSfhlDLw=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0415616', '108.1598646')",
            type_activity: "Du lịch văn hóa & nghệ thuật",
            openTime: "06:00",
            closeTime: "19:00",
          },
        ],
        hotel: {
          id: 14,
          name: "Liberty Hotel Saigon Parkview",
          price: 1295503,
          rating: 7.8,
          address: "Đà Nẵng",
        },
        transport: {
          flights: [
            {
              departure_airport: {
                name: "Tan Son Nhat International Airport",
                id: "SGN",
                time: "2024-05-24 08:05",
              },
              arrival_airport: {
                name: "Da Nang International Airport",
                id: "DAD",
                time: "2024-05-24 09:30",
              },
              duration: 85,
              airplane: "Airbus A321",
              airline: "Vietravel Airlines",
              airline_logo:
                "https://www.gstatic.com/flights/airline_logos/70px/VU.png",
              travel_class: "Economy",
              flight_number: "VU 672",
              extensions: ["Carbon emissions estimate: 76 kg"],
            },
          ],
          total_duration: 85,
          carbon_emissions: {
            this_flight: 76000,
            typical_for_this_route: 78000,
            difference_percent: -3,
          },
          price: 2156080,
          type: "Round trip",
          airline_logo:
            "https://www.gstatic.com/flights/airline_logos/70px/VU.png",
          departure_token:
            "WyJDalJJYldScmFqWlVMVWd4UXpoQlEwbDRaRkZDUnkwdExTMHRMUzB0TFc5NWRtWXlNVUZCUVVGQlIxcE5XR05KUjIxc2VITkJFZ1ZXVlRZM01ob01DTERNZ3dFUUFCb0RWazVFT0J4d2xFST0iLFtbIlNHTiIsIjIwMjQtMDUtMjQiLCJEQUQiLG51bGwsIlZVIiwiNjcyIl1dXQ==",
        },
        total: 170000,
      },
      {
        activities: [
          {
            id: 634,
            name: "Bảo tàng Đà Nẵng",
            rating: 4,
            num_comment: 1800,
            price: 20000,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipOYN3XIgJ6KheNrpDdnK0ffkoZZ9fkWG2wCzkE6=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0764304', '108.1390849')",
            type_activity: "Du lịch văn hóa & nghệ thuật",
            openTime: "08:00",
            closeTime: "17:00",
          },
          {
            id: 620,
            name: "Bảo tàng Mỹ thuật Đà Nẵng",
            rating: 4.4,
            num_comment: 867,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipMhHD8Vd_sobSHFfzymhzdVFScwDroyjVKHO4_r=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0711719', '108.1355393')",
            type_activity: "Du lịch văn hóa & nghệ thuật",
            openTime: "08:00",
            closeTime: "17:00",
          },
          {
            id: 611,
            name: "Chợ Hàn",
            rating: 3.9,
            num_comment: 28000,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipPbZzr5tU8JU-e3aCbjfRFK_a4TxXxsMqFbnDLY=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0681801', '108.1418199')",
            type_activity: "Du lịch văn hóa & nghệ thuật",
            openTime: "06:00",
            closeTime: "19:00",
          },
          {
            id: 634,
            name: "Bảo tàng Đà Nẵng",
            rating: 4,
            num_comment: 1800,
            price: 20000,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipOYN3XIgJ6KheNrpDdnK0ffkoZZ9fkWG2wCzkE6=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0764304', '108.1390849')",
            type_activity: "Du lịch văn hóa & nghệ thuật",
            openTime: "08:00",
            closeTime: "17:00",
          },
          {
            id: 620,
            name: "Bảo tàng Mỹ thuật Đà Nẵng",
            rating: 4.4,
            num_comment: 867,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipMhHD8Vd_sobSHFfzymhzdVFScwDroyjVKHO4_r=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0711719', '108.1355393')",
            type_activity: "Du lịch văn hóa & nghệ thuật",
            openTime: "08:00",
            closeTime: "17:00",
          },
          {
            id: 608,
            name: "Giáo Xứ Chính Toà Đà Nẵng",
            rating: 4.4,
            num_comment: 1000,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipMOFpSG2yBE4HmugzkjGFaNJvouLAgn1Y6lc7po=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0666664', '108.1408159')",
            type_activity: "Du lịch tâm linh",
            openTime: "07:00",
            closeTime: "18:00",
          },
          {
            id: 590,
            name: "Cầu Sông Hàn",
            rating: 4.6,
            num_comment: 4300,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipPR0yFg71ydHaR3xXbbMApGnySOSmF5IBCXeWmc=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.072102', '108.1444452')",
            type_activity: "Vãn cảnh & Check-in",
            openTime: "07:00",
            closeTime: "17:00",
          },
          {
            id: 620,
            name: "Bảo tàng Mỹ thuật Đà Nẵng",
            rating: 4.4,
            num_comment: 867,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipMhHD8Vd_sobSHFfzymhzdVFScwDroyjVKHO4_r=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0711719', '108.1355393')",
            type_activity: "Du lịch văn hóa & nghệ thuật",
            openTime: "08:00",
            closeTime: "17:00",
          },
          {
            id: 604,
            name: "Chợ Cồn",
            rating: 4.2,
            num_comment: 16000,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipPQil9Tr-ZhS6ZyeB_JssO0_ckiL9mepbinePin=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0677202', '108.1320649')",
            type_activity: "Du lịch văn hóa & nghệ thuật",
            openTime: "07:00",
            closeTime: "19:00",
          },
          {
            id: 620,
            name: "Bảo tàng Mỹ thuật Đà Nẵng",
            rating: 4.4,
            num_comment: 867,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipMhHD8Vd_sobSHFfzymhzdVFScwDroyjVKHO4_r=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0711719', '108.1355393')",
            type_activity: "Du lịch văn hóa & nghệ thuật",
            openTime: "08:00",
            closeTime: "17:00",
          },
          {
            id: 605,
            name: "Cầu Tình Yêu Đà Nẵng",
            rating: 4.4,
            num_comment: 2900,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipPnbHQwz-1XWuv7ys_pGrD9ZcvrqueahyBDxZ-X=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0631961', '108.1471896')",
            type_activity: "Vãn cảnh & Check-in",
            openTime: "07:00",
            closeTime: "12:00",
          },
          {
            id: 623,
            name: "Chợ Đêm Sơn Trà",
            rating: 4,
            num_comment: 8400,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipPszW-wO0KJr897Iq0q8ksQF3bun4idkiYGUC1H=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.061582', '108.1495837')",
            type_activity: "Du lịch văn hóa & nghệ thuật",
            openTime: "18:00",
            closeTime: "00:00",
          },
          {
            id: 622,
            name: "Charming Danang Show",
            rating: 3.9,
            num_comment: 745,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipOu-k4P_bA4hiJWHrtSup_9-CLCVjYDnj5rFAzq=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0267031', '108.1385502')",
            type_activity: "Du lịch văn hóa & nghệ thuật",
            openTime: "07:00",
            closeTime: "17:00",
          },
          {
            id: 588,
            name: "Asia Park - Công viên Châu Á",
            rating: 4.4,
            num_comment: 9700,
            price: 150000,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipNY92dZpYZyZf8Qc8iGcO5FhWf-BBSV5bOPUkSl=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0382391', '108.1458155')",
            type_activity: "Du lịch giải trí",
            openTime: "15:00",
            closeTime: "22:00",
          },
          {
            id: 621,
            name: "Chợ đêm Helio (Khu Ẩm thực đêm Helio）",
            rating: 4.1,
            num_comment: 5000,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipOYdBvPT7Eg6HumRdGpZy1aaN3AMKgzz_yxWp5G=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.037228', '108.1420796')",
            type_activity: "Du lịch văn hóa & nghệ thuật",
            openTime: "17:30",
            closeTime: "22:30",
          },
          {
            id: 622,
            name: "Charming Danang Show",
            rating: 3.9,
            num_comment: 745,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipOu-k4P_bA4hiJWHrtSup_9-CLCVjYDnj5rFAzq=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0267031', '108.1385502')",
            type_activity: "Du lịch văn hóa & nghệ thuật",
            openTime: "07:00",
            closeTime: "17:00",
          },
          {
            id: 588,
            name: "Asia Park - Công viên Châu Á",
            rating: 4.4,
            num_comment: 9700,
            price: 150000,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipNY92dZpYZyZf8Qc8iGcO5FhWf-BBSV5bOPUkSl=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0382391', '108.1458155')",
            type_activity: "Du lịch giải trí",
            openTime: "15:00",
            closeTime: "22:00",
          },
          {
            id: 614,
            name: "Chợ Bắc Mỹ An",
            rating: 4.3,
            num_comment: 3800,
            price: 0,
            image:
              "https://lh5.googleusercontent.com/p/AF1QipN4erhNPoFU26rHO2ocWr-wSXyChTqGPSfhlDLw=w148-h148-n-k-no",
            address: "Đà Nẵng",
            distance: "('16.0415616', '108.1598646')",
            type_activity: "Du lịch văn hóa & nghệ thuật",
            openTime: "06:00",
            closeTime: "19:00",
          },
        ],
        hotel: {
          id: 249,
          name: "La Nube Residence",
          price: 483503,
          rating: 8.6,
          address: "Đà Nẵng",
        },
        transport: {
          flights: [
            {
              departure_airport: {
                name: "Tan Son Nhat International Airport",
                id: "SGN",
                time: "2024-05-24 08:05",
              },
              arrival_airport: {
                name: "Da Nang International Airport",
                id: "DAD",
                time: "2024-05-24 09:30",
              },
              duration: 85,
              airplane: "Airbus A321",
              airline: "Vietravel Airlines",
              airline_logo:
                "https://www.gstatic.com/flights/airline_logos/70px/VU.png",
              travel_class: "Economy",
              flight_number: "VU 672",
              extensions: ["Carbon emissions estimate: 76 kg"],
            },
          ],
          total_duration: 85,
          carbon_emissions: {
            this_flight: 76000,
            typical_for_this_route: 78000,
            difference_percent: -3,
          },
          price: 2156080,
          type: "Round trip",
          airline_logo:
            "https://www.gstatic.com/flights/airline_logos/70px/VU.png",
          departure_token:
            "WyJDalJJYldScmFqWlVMVWd4UXpoQlEwbDRaRkZDUnkwdExTMHRMUzB0TFc5NWRtWXlNVUZCUVVGQlIxcE5XR05KUjIxc2VITkJFZ1ZXVlRZM01ob01DTERNZ3dFUUFCb0RWazVFT0J4d2xFST0iLFtbIlNHTiIsIjIwMjQtMDUtMjQiLCJEQUQiLG51bGwsIlZVIiwiNjcyIl1dXQ==",
        },
        total: 230000,
      },
    ],
  },
};
